### ISSUE TITLE
Implement GIN

### ISSUE THREAD

**Issue by robertness** [py-why/dodiscover#1]
Implement the GIN causal discovery algorithm.  GIN learns latent causes that cluster observed variables.  I also learns causal orderings between those latent causes.

References:

- Xie, Cai, Huang, Glymour, Hao, Zhang, "Generalized Independent Noise Condition for Estimating Linear Non-Gaussian Latent 
- Variable Causal Graphs," NeurIPS 2020
- Cai, Xie, Glymour, Hao, Zhang, “Triad Constraints for Learning Causal Structure of Latent Variables,“ NeurIPS 2019

**Comment by adam2392** [comment]
Closed by #94
