### ISSUE TITLE
Pre-fit propensity score model?

### ISSUE THREAD

**Issue by ebridge2** [py-why/dodiscover#105]
**Is your feature request related to a problem? Please describe.**
If one has already fit a propensity score model, it would be helpful to be able to pass it in.

**Describe the solution you'd like**
some sort of API to provide a pre-fit propensity score model.

**Comment by adam2392** [comment]
Adding some info: this is for the KernelCDTest

Also adding it would be nice to be able to specify something besides `LogisticRegression` (i.e. you can specify the ML model to use to fit propensity) inside the KernelCDTest.
