### ISSUE TITLE
[BUG] R8 does a check for a tail incorrectly

### ISSUE THREAD

**Issue by adam2392** [py-why/dodiscover#114]
In https://github.com/py-why/dodiscover/blob/5f5003ecaef7133a25919c72718cd671b9cd49fc/dodiscover/constraint/fcialg.py#L557-L559, the check is incorrect. I should've caught this, but to check `A -> u` in a PAG, one must check that A has directed edge to u AND u does not have a circle edge to A. This is by construction that `A -> u` is compatible with `A o-> u`.

In contrast, `A -o u` is defined as A has a circular edge to u.

It seems this line was reverted in https://github.com/py-why/dodiscover/pull/106/files, which was correct.

```
# check that A -> u -> C
             condition_one = graph.has_edge(a, u, graph.directed_edge_name) and not graph.has_edge(
                 u, a, graph.circle_edge_name
```

cc: @jaron-lee 

This is making me think that the API for querying edges could be more robust. As in there should be a function for causal graphs that queries `has_no_other_edge(u, a)`, which means there must be no other edge from `u` to `a`. This then can be paired with things like checking `has_edge(a, u, circle_edge)`, which implies this is purely a `a -o u` edge.

## Checklist

- [ ] I have verified that the issue exists against the `main` branch.
- [ ] I have read the relevant section in the [contribution guide](https://github.com/py-why/dodiscover/blob/main/CONTRIBUTING.md#bug-reports-and-feature-requests) on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/py-why/dodiscover/issues) for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/py-why/dodiscover/pulls) for existing proposed fixes.
- [ ] I have checked the [CHANGELOG](https://github.com/py-why/dodiscover/blob/main/CHANGELOG.md) and the [commit log](https://github.com/py-why/dodiscover/commits/main) to find out if the bug was already fixed in the main branch.
- [ ] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [ ] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [ ] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [ ] I have included in the "Environment" section below the output of `pip freeze`.
- [ ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS:

Python version:

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```

</p>
</details>

**Comment by adam2392** [comment]
This is the correct replacement:

```
            # check that A -> u
            condition_one_Adirectu = (graph.has_edge(a, u, graph.directed_edge_name) and not graph.has_edge(
                 u, a, graph.circle_edge_name))
            # check that A -o u
            condition_one_Acircleu = (graph.has_edge(a, u, graph.circle_edge_name) and not graph.has_edge(u, a))
            if self.selection_bias:
                condition_one = condition_one_Adirectu or condition_one_Acircleu
            else:
                condition_one = condition_one_Adirectu
```

I have yet to verify R5-7 tho. But I think what I can do is help document the internal rules setting for different edges:

- `->`: is a directed edge present? (note no other edge should be present in other direction)
- `<->`: is bidirected edge present? (note no other edge should be present in any other direction)
- `-`: is tail edge present? (note no other edge should be present in any other direction)
- `o-o`: is circle edge present in both directions?
- `o->`: is circle edge one way and directed edge another way?
- `o-`: is there only one circle edge? (note no other edge should be present in other direction)

**Comment by jaron-lee** [comment]
Ah good catch. I agree that the API sucks, I did have a lot of trouble checking o-> type edges.

**Comment by adam2392** [comment]
I can push up a fix for R8 and the corresponding test

**Comment by jaron-lee** [comment]
ah okay I'm happy to do it if you like

**Comment by adam2392** [comment]
Ah sure yeah that would be great! I caught this when I was implementing Psi-FCI for interventional data, so the fix from me wouldn't come for awhile

**Comment by jaron-lee** [comment]
Did you happen to have a test case that I can add to the unit tests? I can come up with one if not

**Comment by adam2392** [comment]
Yes you can add the following to `test_fcialg.py`

```Python

@pytest.mark.parametrize(
    "skeleton_method", [SkeletonMethods.NBRS, SkeletonMethods.COMPLETE]
)
@pytest.mark.parametrize("pds_skeleton_method", [SkeletonMethods.PDS])
def test_fci_complex(skeleton_method, pds_skeleton_method):
    """
    Test FCI algorithm with more complex graph.

    Use Figure 2 from :footcite:`Colombo2012`.

    References
    ----------
    .. footbibliography::
    """
    edge_list = [
        ("x4", "x1"),
        ("x2", "x5"),
        ("x3", "x2"),
        ("x3", "x4"),
        ("x2", "x6"),
        ("x3", "x6"),
        ("x4", "x6"),
        ("x5", "x6"),
    ]
    latent_edge_list = [("x1", "x2"), ("x4", "x5")]
    G = ADMG(edge_list, latent_edge_list)
    sample = dummy_sample(G)
    context = make_context().variables(data=sample).build()
    oracle = Oracle(G)
    ci_estimator = oracle
    fci = FCI(
        ci_estimator=ci_estimator,
        max_iter=np.inf,
        skeleton_method=skeleton_method,
        pds_skeleton_method=pds_skeleton_method,
        selection_bias=False,
    )
    fci.fit(sample, context)
    pag = fci.graph_

    # double check the m-separation statement and PDS
    assert pywhy_nx.m_separated(G, {"x1"}, {"x3"}, {"x4"})
    pdsep = pywhy_graphs.pds(G, "x1", "x3")
    assert "x2" in pdsep

    expected_pag = PAG()
    expected_pag.add_edges_from(
        [("x6", "x5"), ("x2", "x3"), ("x4", "x3"), ("x6", "x4")], expected_pag.circle_edge_name
    )
    expected_pag.add_edges_from(
        [
            ("x4", "x1"),
            ("x2", "x5"),
            ("x3", "x2"),
            ("x3", "x4"),
            ("x2", "x6"),
            ("x3", "x6"),
            ("x4", "x6"),
            ("x5", "x6"),
        ],
        expected_pag.directed_edge_name,
    )
    expected_pag.add_edge("x1", "x2", expected_pag.bidirected_edge_name)
    expected_pag.add_edge("x4", "x5", expected_pag.bidirected_edge_name)

    assert set(pag.edges()) == set(expected_pag.edges())
    for edge_type, subgraph in expected_pag.get_graphs().items():
        assert nx.is_isomorphic(subgraph, pag.get_graphs(edge_type))
```

The check does two things: 1) it improves coverage of the algorithm and 2) it adds the subgraph isomorphism check so that all edge-type subgraphs are the same. I am also pushing up a PR to pywhy-graphs to start adding more documentation at least for this issue. I suspect the API will evolve as we progress, but at least we'll have a working prototype and unit tests :)

**Comment by jaron-lee** [comment]
Great, I added my own simple test as well. For bug fixes should I also update the changelog?

**Comment by adam2392** [comment]
Nah, until we get into release cycles prolly unnecessary.

**Comment by jaron-lee** [comment]
Should I add this test as-is or should I modify the existing `Test_FCI.test_fci_complex` test? Seems to be a lot of overlap

**Comment by jaron-lee** [comment]
I will modify existing test in the initial PR, we can change if you disagree

**Comment by adam2392** [comment]
Sounds good!
