### ISSUE TITLE
Introduce pre-commit hooks

### ISSUE THREAD

**Issue by jaron-lee** [py-why/dodiscover#116]
Problem:
 For new contributors it can be difficult to remember to comply with the various repository requirements on linting, code formatting etc. whilst also debugging technical issues. There exists various poetry commands such as `poetry run poe apply_format` but there are several of these and it is easy to forget one or more during a PR.

Proposed fix:

Implement pre-commit hooks to automatically run the poetry commands.

Other considered solutions:

Could continue with the current system but this wastes CI cycles if a contributor forgets to run the various poetry commands.

Notes:

> Yeah will fix it up. Is there a system that you have for running these before you push? I always forget to run one or more of these commands, would be interested to learn if there are better ways than trying to remember to do this.

We can look into a precommit hook similar to networkx: 

https://github.com/networkx/networkx/blob/main/.pre-commit-config.yaml

Down to have this added.

_Originally posted by @adam2392 in https://github.com/py-why/dodiscover/issues/115#issuecomment-1430085018_

**Comment by jaron-lee** [comment]
Will be required to increment isort version due to this issue: https://github.com/home-assistant/core/issues/86892

**Comment by adam2392** [comment]
That is fine. We can probably upgrade all isort,black, mypy, flake8 and pydocstyle to their most recent versions.

**Comment by jaron-lee** [comment]
Found https://github.com/floatingpurr/sync_with_poetry which pulls the version numbers from `poetry.lock` so we don't have to duplicate version specifications
