### ISSUE TITLE
NoGAM

### ISSUE THREAD

**Issue by lww28** [py-why/dodiscover#134]
The paper titled "Causal Discovery with Score Matching on Additive Models with Arbitrary Noise" mentions that the code for NoGAM can be found in the DoDiscover library, which is available at https://www.pywhy.org/dodiscover/dev/index.html. However, I could not find the corresponding code. Can I know where it is? Thank you!!

**Comment by adam2392** [comment]
It's being developed in a PR rn.

**Comment by adam2392** [comment]
The PR has been merged, so closing this issue.
