### ISSUE TITLE
Subclass PC algorthm so it's the more traditional PC algorithm

### ISSUE THREAD

**Issue by robertness** [py-why/dodiscover#38]
Ask @adam2392 for details.  Involves refactoring how the algorithm deals with colliders.  Requires only one method to be rewritten.

**Comment by adam2392** [comment]
@robertness I think I am not following what was stated here. The current PC algorithm is the original one implemented. Is there an even more "OG one"?

I'm trying to clean up these issues for first contributors. I think they'll need a bit more info and outline, unless they're pretty knowledgable already.

**Comment by adam2392** [comment]
I am closing this one as IIUC, the PC algorithm we have implemented is the "traditional one".
