### ISSUE TITLE
Implement R5-7 for selection bias in FCI algorithm

### ISSUE THREAD

**Issue by adam2392** [py-why/dodiscover#53]
**Is your feature request related to a problem? Please describe.**
Currently, the FCI algorithm implementation does not implement R5-8 in the FCI algorithm, which accounts for learning graphs with selection bias.

It would be a straightforward issue for someone to add these into the existing implementation. 

**Describe the solution you'd like**
Implement R5-8 of the FCI algorithm. See [publication](https://reader.elsevier.com/reader/sd/pii/S0004370208001008?token=5E04A22E2DE4FB1F3406C7CA0456B121D2E8E0019892D2EDB3260BB614D415B4DF520F9E79670883E8F2586A90E6143C&originRegion=us-east-1&originCreation=20220928184705).

- Implement `_apply_rule5`, `_apply_rule6` and `_apply_rule7`
- Update logic inside `_apply_rules_1to10`
- add unit tests to `tests/unit_tests/constraint/test_fcialg.py`
- [Bonus] Implement an example going through the different caveats and concepts of the FCI algorithm

Probably the most involved would be implementing the unit tests. The current graph API is a work in progress.

**Comment by jaron-lee** [comment]
I'm happy to take a stab at this!

**Comment by jaron-lee** [comment]
One question I do have - for R5 we require a function to check if there exists an uncovered circle path between two nodes. I found a similar function `uncovered_pd_path` at `pywhy_graphs/algorithms/pag.py` - would the best way be for me to modify that function and create a corresponding PR in `pywhy_graphs`?

**Comment by adam2392** [comment]
> One question I do have - for R5 we require a function to check if there exists an uncovered circle path between two nodes. I found a similar function `uncovered_pd_path` at `pywhy_graphs/algorithms/pag.py` - would the best way be for me to modify that function and create a corresponding PR in `pywhy_graphs`?

The `uncovered_pd_path` is used for the R8-10 section where we need an uncovered potentially directed path. If the internals work the same for doing it for a circle path, then yeah that sounds good!

I could see a few solutions:
1. implement a separate function altogether
2. refactor `uncovered_pd_path` to find either uncovered pd paths, or uncovered circle paths

I'll migrate an issue over there. I'm happy to review a PR once you get started @jaron-lee !

**Comment by adam2392** [comment]
https://github.com/py-why/pywhy-graphs/pull/42 has been completed now
