### ISSUE TITLE
Update how to get parameters of a context to facilitate "copying"

### ISSUE THREAD

**Issue by adam2392** [py-why/dodiscover#62]
Currently, we do copying of Context within the `ContextBuilder`. I think this is fine for simplifying the API of the `Context`, but I think adding new properties to `Context` then necessarily means we update this one area of copying. It is possible that there are bugs that are introduced. 

```
def make_context(context: Optional[Context] = None) -> ContextBuilder:
    result = ContextBuilder()
    if context is not None:
    # this part needs to be updated manually every time
        result.graph(deepcopy(context.init_graph))
        result.edges(deepcopy(context.included_edges), deepcopy(context.excluded_edges))
        result.variables(copy(context.observed_variables), copy(context.latent_variables))
        result.state_variables(deepcopy(context.state_variables))
    return result
```

Instead, I propose to dynamically get all possible parameter names similar to how [scikit-learn does it](https://scikit-learn.org/stable/developers/develop.html#get-params-and-set-params). We would add `_get_params()` and `_set_params()` to the `Context` class, and then change the above LOC to:

```
def make_context(context: Optional[Context] = None) -> ContextBuilder:
    result = ContextBuilder()
    if context is not None:
        context_params = context.get_params()
        result.set_params(context_params)
    return result
```

We can make `get_params/set_params` private to discourage users from manipulating their context classes themselves.

cc: @robertness @darthtrevino

**Comment by darthtrevino** [comment]
I like this, so `get_params` will clone your parameter objects into a plain object representation? I don't even think they need to be private, that seems like it could be generally useful for debug.

**Comment by adam2392** [comment]
Yep! so `get_params` would return a dictionary object of {<paramter_name>: <parameter_value>}, which can be essentially directly passed to `ContextBuilder.set_params`. The difference from sklearn is that we are using a builder API design rather than a traditional keyword argument parameter design, so the internals will be slightly different.

However, the API of these 2 functions if robust would enable us to easily catch any incongruiencies whenever a new attribute is added to Context.
